services:
  mitemp2:
    image: mitemp2
    logging:
        driver: none
    restart: unless-stopped
    container_name: mitemp2
    volumes:
      - ../sensors.ini:/app/sensors.ini
      - ../sendToInflux.sh:/app/sendToInflux.sh
      - ./entrypoint.sh:/app/entrypoint.sh
    # host network mode and the NET_RAW and NET_ADMIN are required for
    #  BLE scanning to work (or alternatively privileged mode)
    privileged: true
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
